[buildPlans.IoTerminaMindless]
family = "Io Termina Mindless"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IoTerminaMindless.variants]
  inherits = "ss14"

    [buildPlans.IoTerminaMindless.variants.design]
    one = "base"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    nine = "straight-bar"
    zero = "dotted"
    capital-a = "round-top-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "flat-hook-serifed"
    capital-k = "symmetric-connected-serifless"
    capital-q = "curly-tailed"
    capital-r = "standing-serifless"
    capital-u = "toothless-rounded-serifless"
    capital-w = "straight-vertical-sides-serifless"
    a = "double-storey-toothless-rounded"
    b = "toothless-rounded-serifless"
    d = "toothless-rounded-serifless"
    g = "single-storey-flat-hook-earless-rounded"
    i = "serifed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "earless-rounded-straight-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-straight-serifless"
    r = "compact-serifless"
    t = "flat-hook-short-neck"
    w = "rounded-vertical-sides-serifless"
    y = "cursive-flat-hook-serifless"
    z = "straight-serifless"
    tittle = "round"
    diacritic-dot = "round"
    underscore = "high"
    brace = "straight"
    at = "fourfold-solid-inner"
    dollar = "open"
    cent = "open"
    bar = "natural-slope"
    question = "corner-flat-hooked"

    [buildPlans.IoTerminaMindless.variants.italic]
    one = "base"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    six = "open-contour"
    seven = "straight-serifless"
    nine = "open-contour"
    capital-a = "round-top-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-l = "serifless"
    capital-q = "curly-tailed"
    capital-r = "standing-serifless"
    capital-w = "straight-vertical-sides-serifless"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    f = "flat-hook-tailed"
    g = "single-storey-earless-corner"
    h = "straight-serifless"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "earless-corner-double-arch-short-leg-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "compact-serifless"
    t = "flat-hook"
    w = "rounded-vertical-sides-serifless"
    y = "cursive-serifless"
    tittle = "round"
    diacritic-dot = "round"
    underscore = "low"
    paren = "flat-arc"
    brace = "straight"
    at = "fourfold-solid-inner"
    dollar = "open"
    cent = "open"
    bar = "natural-slope"
    question = "smooth"

  [buildPlans.IoTerminaMindless.ligations]
  inherits = "dlig"

[buildPlans.IoTerminaMindless.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoTerminaMindless.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IoTerminaMindless.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.IoTerminaMindless.weights.ExtraBold]
shape = 800
menu = 800
css = 800

[buildPlans.IoTerminaMindless.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoTerminaMindless.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IoTerminaMindless.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IoTerminaMindless.metricOverride]
parenSize = 860
