[buildPlans.IoTerminaMindless]
family = "Io Termina Mindless"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IoTerminaMindless.variants]
  inherits = "ss14"

    [buildPlans.IoTerminaMindless.variants.design]
    one = "base"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    six = "straight-bar"
    seven = "straight-serifed"
    nine = "straight-bar"
    zero = "dotted"
    capital-a = "round-top-serifless"
    capital-g = "toothless-rounded-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "flat-hook-serifed"
    capital-k = "symmetric-connected-serifless"
    capital-q = "curly-tailed"
    capital-r = "standing-serifless"
    capital-u = "toothless-rounded-serifless"
    capital-w = "straight-vertical-sides-serifless"
    a = "double-storey-toothless-rounded"
    b = "toothless-rounded-serifless"
    d = "toothless-rounded-serifless"
    g = "single-storey-flat-hook-earless-rounded"
    i = "serifed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    m = "earless-rounded-double-arch-short-leg-serifless"
    n = "earless-rounded-straight-serifless"
    p = "earless-rounded-serifless"
    q = "earless-rounded-straight-serifless"
    r = "compact-serifless"
    t = "flat-hook-short-neck"
    w = "rounded-vertical-sides-serifless"
    y = "cursive-flat-hook-serifless"
    z = "straight-serifless"
    eszet = "longs-s-lig-serifless"
    lower-alpha = "barred-earless-rounded-tailed"
    lower-beta = "standard"
    lower-delta = "rounded"
    lower-eta = "earless-rounded-serifless"
    lower-mu = "toothless-rounded-serifless"
    partial-derivative = "curly-bar"
    cyrl-a = "double-storey-toothless-rounded"
    cyrl-ve = "cursive"
    cyrl-capital-zhe = "cursive"
    cyrl-zhe = "cursive"
    cyrl-er = "earless-rounded-serifless"
    cyrl-capital-u = "cursive-flat-hook-serifless"
    cyrl-u = "cursive-flat-hook-serifless"
    cyrl-ef = "serifless"
    cyrl-yeri = "round"
    cyrl-yery = "round-tailed"
    cyrl-capital-ya = "standing-serifless"
    cyrl-ya = "standing-serifless"
    tittle = "round"
    diacritic-dot = "round"
    underscore = "high"
    brace = "straight"
    at = "fourfold-solid-inner"
    dollar = "open"
    cent = "open"
    bar = "natural-slope"
    question = "corner-flat-hooked"

    [buildPlans.IoTerminaMindless.variants.italic]
    one = "base"
    two = "curly-neck-serifless"
    three = "flat-top-serifless"
    six = "open-contour"
    seven = "straight-serifless"
    nine = "open-contour"
    capital-a = "round-top-serifless"
    capital-g = "toothless-corner-serifless-hooked"
    capital-i = "short-serifed"
    capital-j = "serifed"
    capital-k = "symmetric-connected-serifless"
    capital-l = "serifless"
    capital-q = "curly-tailed"
    capital-r = "standing-serifless"
    capital-u = "toothless-corner-serifless"
    capital-w = "straight-vertical-sides-serifless"
    a = "double-storey-toothless-corner"
    b = "toothless-corner-serifless"
    d = "toothless-corner-serifless"
    f = "flat-hook-tailed"
    g = "single-storey-earless-corner"
    h = "straight-serifless"
    i = "serifed-flat-tailed"
    j = "flat-hook-serifed"
    k = "symmetric-connected-serifless"
    l = "serifed-flat-tailed"
    m = "earless-corner-double-arch-short-leg-serifless"
    n = "earless-corner-straight-serifless"
    p = "earless-corner-serifless"
    q = "earless-corner-straight-serifless"
    r = "compact-serifless"
    t = "flat-hook"
    u = "toothless-corner-serifless"
    w = "rounded-vertical-sides-serifless"
    y = "cursive-serifless"
    lower-alpha = "barred-earless-corner-tailed"
    lower-eta = "earless-corner-serifless"
    lower-iota = "serifed-semi-tailed"
    lower-mu = "toothless-corner-serifless"
    lower-tau = "flat-tailed"
    lower-upsilon = "casual-serifless"
    cyrl-a = "double-storey-toothless-corner"
    cyrl-er = "earless-corner-serifless"
    cyrl-capital-u = "cursive-serifless"
    cyrl-u = "cursive-serifless"
    cyrl-ef = "cursive"
    tittle = "round"
    diacritic-dot = "round"
    underscore = "low"
    ascii-grave = "straight"
    paren = "flat-arc"
    brace = "straight"
    at = "fourfold-solid-inner"
    dollar = "open"
    cent = "open"
    bar = "natural-slope"
    question = "smooth"

  [buildPlans.IoTerminaMindless.ligations]
  inherits = "dlig"

[buildPlans.IoTerminaMindless.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IoTerminaMindless.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IoTerminaMindless.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.IoTerminaMindless.weights.Heavy]
shape = 900
menu = 900
css = 900

[buildPlans.IoTerminaMindless.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IoTerminaMindless.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IoTerminaMindless.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IoTerminaMindless.metricOverride]
parenSize = 860
